INSERT INTO public.medidas (id_medida,id_organismo,referencia_pda,tipo_medida,nombre_corto,indicador,formula,frecuencia,verificacion,regulatoria) VALUES
	 (1,12,'42, 43, 44','','RCA que contenga obligación de compensar emisiones.','Número de RCA aprobadas en el año t que contengan obligaciones de compensar emisiones atmosféricas.','Suma del número de RCA aprobadas que contengan obligación de compensar emisiones atmosféricas.','Anual.','Registro de las RCA aprobadas identificando el titular, la RCA, las emisiones y el monto a compensar.','Regulatoria'),
	 (2,13,'33.37','','Condiciones del sistema de recuperación y/o eliminación de vapores de estanques Depósito techo fijo.','Cumplimiento de las condiciones indicadas en el literal A) para depósitos de techo fijo y Cronograma de implementación gradual calificado por la SEC cuando corresponda','([N° de tanques del artículo 33 literal A) al cual se han implementado las medidas comprometidas en el año t]/ [N° de tanques del artículo 33 literal A) programadas para el año t]) *100','Anual','a) Informe de Avance de Implementación de las medidas del Plan. b) En caso de solicitar más plazo, Oficio de envío de la Resolución que califica el Cronograma de implementación gradual para el plazo de cumplimiento.','Regulatoria'),
	 (3,13,'33.37','','Requisitos del sistema de almacenamiento intermedio','Instrucciones de SEC, para cumplir con el sistema de almacenamiento intermedio u otro con el mismo objetivo, conforme al artículo 5 del DS N°160/2008','Si/No','Única','Oficialización de la instrucción de SEC para cumplir con el sistema indicado en el artículo 33 del Plan.','Regulatoria'),
	 (4,13,'33.37','','Aprobación de sistema de almacenamiento intermedio','N° de instalaciones con estanque que cuenten con un sistema de almacenamiento intermedio u otro que cumpla con el objetivo aprobado.','Si/No','Única','Resolución que aprueba por la SEC, el sistema intermedio u otro que cumpla con el mismo objetivo','Regulatoria'),
	 (5,13,'33.37','','Condiciones del sistema de recuperación y/o eliminación de vapores de estanques Deposito de techo flotante','Cumplimiento de las condiciones indicadas en el literal B) para depósitos de techo flotante y Cronograma de implementación gradual calificado por la SEC, cuando corresponda.','([N° de tanques a los cuales se les implementaron sellos primarios y/o secundarios l en el año t] / [N° de tanques programados implementados en el año t]) * 100.','Anual','a) Informe de avance de implementación de las medidas del articulo 33 del plan. b) En caso de solicitar más plazo, Oficio de envío de la Resolución que califica el cronograma de implementación gradual para el plazo de cumplimiento.','Regulatoria'),
	 (6,13,'34','','Sistema de recuperación y eliminación de vapores en fuentes emisoras de HC','N° de sistemas capaz de recuperar y/o eliminar vapores que se generen en los procesos de carga y descarga, transporte, almacenamiento, distribución y abastecimiento de HC y sus derivados, en el año t.','([N° de sistemas de recuperación y/o eliminación de vapores mantenidos con TK mayores a 200m3] / [N° de sistemas de recuperación y/o eliminación de vapores existentes en instalaciones con TK mayores a 200m3]) *100','Anual','Programa de mantención y operación de los dispositivos y/o infraestructura, recepcionado hasta mayo de cada año a la SEC.','Regulatoria'),
	 (7,13,'34','','Almacenamiento, distribución de combustibles líquidos','Número de fiscalizaciones a las obligaciones del art. 177 letra g) del DS N°160/2008 Ministerio de Economía y Fomento y Reconstrucción, en el año t.','Suma del número de fiscalizaciones ejecutadas en el año t a instalaciones de almacenamiento y distribución de combustible','Anual','a) Registro interno del servicio con el número de fiscalizaciones ejecutadas a instalaciones de almacenamiento y distribución de combustibles líquidos. b) Programa de mantención y operación de los dispositivos y/o infraestructura, recepcionado hasta mayo de cada año a la SEC.','Regulatoria'),
	 (8,13,'35','','Sistemas de venteo dotados de piloto manual y automático','N° de Instalaciones con antorcha que cuenten con piloto de encendido manual y automático en el sistema de venteo (antorcha).','Si/No','Única','Registro fotográfico del piloto de encendido manual y automático, enviado a la SEC. Registro del sistema de control de los sistemas de encendido, enviado a la SEC.','Regulatoria'),
	 (9,13,'35','','Registro trazable de los flujos másicos del gas piloto y de gas barrido','Numero de fiscalizaciones a establecimientos que cuenten con sistemas de venteo en los que realice quema controlada que den cuenta del registro trazable de los flujos masicos horarios del gas piloto y de gas de barrido.','Suma del número de fiscalizaciones a establecimiento que cuenten con sistema de venteo con quema controlada mediante antorcha','Anual','Registro interno del servicio del número de fiscalizaciones donde se verifico el cumplimiento del registro trazable actualizado, en formato físico y digital.','Regulatoria'),
	 (10,8,'46.d','Política Pública.','Plan Comunicacional respecto de la gestión de episodios críticos.','Implementación de Plan Comunicacional en periodo de gestión de episodios críticos.','SI / No.','Anual','Informe que dé cuenta de la implementación anual del plan comunicacional orientado a la comunidad.','No Regulatoria');
INSERT INTO public.medidas (id_medida,id_organismo,referencia_pda,tipo_medida,nombre_corto,indicador,formula,frecuencia,verificacion,regulatoria) VALUES
	 (11,8,'47, 48','Política Pública.','Declaración de episodios críticos.','Porcentaje de Resoluciones dictadas en relación al número de episodios declarados a la comunidad en el año t.','[Número de resoluciones dictadas] / [Numero de episodios declarados] *100','Anual','Resoluciones que declaran episodios críticos para el año t.','No Regulatoria'),
	 (12,8,'45','Política Pública.','Coordinación de Episodios Críticos.','Programa de coordinación de gestión de Episodios Críticos.','Si / No','Anual','a) Oficialización del programa de coordinación de episodios críticos del año t. b) Informe de resultados del programa de coordinación de episodios críticos del año t.','No Regulatoria'),
	 (13,7,'38','','Medidas para buques que realizan carga y descarga en la bahía-MARPOL','Numero de inspecciones realizadas en el año t al cumplimiento a las exigencias del anexo VI del convenio MARPOL y sus enmiendas, en naves que realicen faenas de carga y descarga en muelles, monoboyas, boyas multipropósito asociados a los terminales marítimos de la bahía de Quinteros','Suma del número de inspecciones realizadas en el año t a naves que realicen faenas de carga y descarga en los terminales marítimos de la bahía de Quinteros','Anual','a) Informe anual que dé cuenta del cumplimiento a las exigencias, sanciones impuestas y nivel de actividad de naves e la Bahía. B) Registro interno de las inspecciones realizadas en el año t en marco del anexo VI del convenio MARPOL','Regulatoria'),
	 (14,6,'39','','Prohibición de uso de fuego para la combustión abierta de rastrojos y de cualquier residuo de origen vegetal agrícola o forestal en el área rural.','Porcentaje de patrullas de detección de quemas no autorizadas ejecutados en el año t en el área del PPDA, respecto del número de patrullajes para detección de quemas no autorizadas programadas en el año t en el área de PPDA.','N° de patrullajes para detección e quemas no autorizadas, ejecutados en el año t en el área del PPDA / N° total de patrullajes patrullajes para detección de quemas no autorizadas, programadas en el año t en el área de PPDA','Anual','Reporte y patrullajes programados para detección de quemas no autorizadas de desechos vegetales agrícolas o forestales efectivamente ejecutados.','Regulatoria'),
	 (15,6,'39','','Autorización excepcional para la quema de rastrojos y de cualquier otro residuos de origen vegetal agrícola o forestal en el área rural','Numero de autorizaciones excepcionales para la ejecución de quemas agrícolas realizadas en el año t','Suma del número de autorizaciones excepcionales para la ejecución de quemas agrícolas realizadas en el año t','Anual','Registro de autorizaciones excepcionales a la ejecución de quemas de rastrojos y cualquier otro residuo de origen vegetal agrícola o forestal en el área rural.','Regulatoria'),
	 (16,11,'39','','Prohibición de uso de fuego para la combustión abierta de rastrojos, hojas secas y de cualquier residuo de origen vegetal o forestal-SAG','Numero de actividades de vigilancia de quemas agrícolas no autorizadas, en territorio rural del PPDA','Suma del número de actividades de vigilancia de quemas agrícolas, en el territorio rural del PPDA, en año t','Anual','Acta de fiscalización transversal (documento interno de registro de actividades de fiscalización)','Regulatoria'),
	 (17,5,'39','','Prohibición de uso de fuego para la combustión abierta de rastrojos, hojas secas y cualquier residuo de origen vegetal o forestal','N° de quemas de rastrojos y de cualquier tipo de vegetación viva o muerta, detectada en los terrenos agrícolas ganaderos o de aptitud preferente forestal detectadas en el año t','Suma del número de quemas en terrenos agrícolas ganaderos o de aptitud preferentemente forestal en el año t','Anual','Registro interno del servicio de cuentas de las quemas agrícolas detectadas en período definido según cronograma quemas de rastrojos','Regulatoria'),
	 (18,10,'27','Política pública','Catastro de plantas de áridos e instalaciones que utilizan áridos','Existencia de Catastro y Diagnóstico de las Plantas de áridos de instalaciones que utilizan áridos para mejoramiento o mantención de superficies metálicas','Sí/No','Única','Oficialización del Catastro de Diagnóstico de las Plantas de áridos e instalaciones que utilizan áridos para mejoramiento o mantención de superficies metálicas','No Regulatoria'),
	 (19,14,'27','','Requisitos para fuentes areales existentes que cuenten con proceso de extracción, molienda harneo de áridos y su uso para mejoramiento de superficies metálicas','Cumplimiento de las medidas listadas en las letras a) a f) del artículo 27 del Plan, para las fuentes areales existentes, en el año t','([N° de titulares de procesos definidos en el art. 27 que implementaron las medidas del artículo 27 literal a) a la f) en el año t]/[N° de titulares de procesos definidos en el artículo 27 que deben cumplir las medidas del literal a) a la f) en el año t])*100','Anual','a) Informe Anual del cumplimiento de las medidas  b) Registro interno de las fiscalizaciones realizadas','Regulatoria'),
	 (20,14,'27','','Requisitos para fuentes areales nuevas que cuenten con proceso de extracción, molienda harneo de áridos y su uso para mejoramiento de superficies metálicas','Cumplimiento de las medidas listadas en las letras a) a f) del artículo 27 del Plan, para las fuentes areales existentes, en el año t','([N° de titulares de procesos definidos en el art. 27 que implementaron las medidas del artículo 27 literal a) a la f) en el año t]/[N° de titulares de procesos definidos en el artículo 27 que deben cumplir las medidas del literal a) a la f) en el año t])*100','Anual','a) Informe Anual de cumplimiento de las medidas. B) Registro interno de las fiscalizaciones realizadas','Regulatoria');
INSERT INTO public.medidas (id_medida,id_organismo,referencia_pda,tipo_medida,nombre_corto,indicador,formula,frecuencia,verificacion,regulatoria) VALUES
	 (21,14,'27','','Programa de fiscalización de áridos','Resultados del Programa de fiscalización diseñado en el año t','Si/No','Anual','a) Oficio de envío a la SMA con el programa de fiscalización a implementar en el año t b) Documento programado de fiscalización a implementar en el año t','Regulatoria'),
	 (22,14,'28','','Control de emisiones MP gráneles sólidos existentes','Cumplimiento de las medidas listadas en las letras a) a g) del artículo 28 del Plan, para las fuentes areales existentes, en el año t','([N° de titulares de instalaciones existentes definidas en el artículo 28 que implementaron las medidas del artículo 28 literal a) a la g) en el año t]/[N° de titulares de instalaciones existentes definidos en el artículo 28 que deben cumplir las medidas del artículo 28 literal a) a la g) fiscalizados en el año t])*100','Anual','Informe Anual del cumplimiento de las medidas','Regulatoria'),
	 (23,14,'28','','Control de emisiones MP gráneles sólidos nuevos','Cumplimiento de las medidas listadas en las letras a) a g) del artículo 28 del Plan, para las fuentes areales nuevas, en el año t','([N° de titulares de instalaciones nuevas definidas en el artículo 28 que implementaron las medidas del artículo 28 literal a) a la g) en el año t]/[N° de titulares de instalaciones nuevas definidos en el artículo 28 que deben cumplir las medidas del artículo 28 literal a) a la g) fiscalizados en el año t])*10','Anual','Informe Anual del cumplimiento de las medidas','Regulatoria'),
	 (24,14,'29','','Control de emisiones de MP en almacenamiento existentes de gráneles sólidos en canchas abiertas','N° de instalaciones existentes que cuenten con un sistema que impida la dispersión del material hacia el exterior, y que cuenten con un mecanismo de verificación de su efectividad, con informe favorable de la SEREMI MA, presentado a la SEREMI de Salud.','Sí/No','Única','a) Informe anual del cumplimiento de las medidas b) Resolución de SEREMI de Salud que aprueba el sistema y el mecanismo de verificación c) Informe favorable de la SEREMI de MA, del sistema y el mecanismo de verificación','Regulatoria'),
	 (25,14,'29','','Control de emisiones de MP en almacenamiento nuevos de gráneles sólidos en canchas abiertas','N° de instalaciones nuevas que cuenten con un sistema que impida la dispersión del material hacia el exterior, y que cuenten con un mecanismo de verificación de su efectividad, con informe favorable de la SEREMI MA, presentado a la SEREMI de Salud.','Sí/No','Única','a) Informe anual del cumplimiento de las medidas b) Resolución de SEREMI de Salud que aprueba el sistema y el mecanismo de verificación c) Informe favorable de la SEREMI de MA, del sistema y el mecanismo de verificación','Regulatoria'),
	 (26,14,'30','','Fuentes Areales (instalaciones existentes que no puedan contar con un sistema de dispersión del art. 29)','N° de pronunciamientos a los informes técnico presentado a la SEREMI de Salud a 2 meses de su ingreso.','Suma del número de pronunciamientos (aprobación/rechazo) de los informes técnicos presentado a la SEREMI de Salud a 2 meses de su ingreso','Única','Resolución que aprueba/rechaza el Informe Técnico que acredita el impedimento de contar con un sistema que impide la dispersión de sus graneles sólidos.','Regulatoria'),
	 (27,14,'32','','Declaración Anual de las emisiones de COVS','Declaración Anual de las emisiones de COVs del año anterior mediante el D.S. N°138/2005 MINSAL, considerando los contenidos del artículo 32 delo Plan, en el año t','Si/No','Anual','a) Registro interno de los establecimientos que presentaron declaración de emisiones de COVs en la zona saturada b) Comprobante de declaraciones de emisiones de COVs en zona de Concón, Quintero y Puchuncaví recepcionadas en la SEREMI de Salud.','Regulatoria'),
	 (28,14,'9','Política Púbica','Registro de calderas histórico','Remisión del listado histórico de calderas registradas de acuerdo al D.S N°10/2012 MINSAL a la SMA','Si/No','Única','a) Oficio de remisión de listado de calderas registradas ingresando a la SMA b) Documento Excel con listado histórico de calderas registradas.','No Regulatoria'),
	 (29,14,'9','Política Púbica','Registro actualizado de calderas','Remisión a la SMA del listado de calderas de acuerdo al D.S N° 10/2012 MINSAL en el año t','Si/No','Anual','a) Oficio de remisión de listado de calderas registradas ingresando a la SMA b) Documento Excel con listado  de calderas registradas en el año t','No Regulatoria'),
	 (30,14,'20','Política Pública','Remisión a la SMA del registro de las fuentes estacionarias','Remisión de información histórica de emisiones, por establecimiento y contaminantes','Si/No','Única','a) Oficio de derivación a la SMA de información histórica de emisiones por establecimientos y contaminante b) Excel con información histórica, por establecimiento y contaminante','No Regulatoria');
INSERT INTO public.medidas (id_medida,id_organismo,referencia_pda,tipo_medida,nombre_corto,indicador,formula,frecuencia,verificacion,regulatoria) VALUES
	 (31,14,'27','Política Pública','Catastro y diagnóstico de plantas de áridos e instalaciones que utilizan áridos','Existencia de Catastro y Diagnóstico de las Plantas de áridos e instalaciones que utilizan áridos para mejoramiento o mantención de superficies metálicas','Si/No','Única','Oficialización del Catastro y Diagnóstico de las Plantas de áridos e instalaciones que utilizan áridos para mejoramiento o mantención de superficies metálicas','No Regulatoria'),
	 (32,9,'48','Política Pública','Modelo de pronóstico de calidad del aire','Oficialización de Modelo pronóstico de Calidad del Aire','Si / No','Única','Existencia de resolución que aprueba metodología de pronóstico de calidad del aire para MP10, MP 2.5 y SO2, en la zona de Concón, Quintero y Puchuncavi','No Regulatoria'),
	 (33,9,'50','Educación y difusión','Traspaso de EMRP al MMA','Número de estaciones de monitoreo EMRP supervisadas por el MMA','[Numero de EMRP cuya administración se traspasó] / [ Numero de EMRP en la zona saturada]','Anual','Documento que oficialice el traspaso de las estaciones por parte de privados al MMA para cada uno de los titulares con estaciones con representatividad poblacional (EMRP)','No Regulatoria'),
	 (34,9,'51','Estudios','Estudios para el rediseño y modernización del monitoreo de la calidad de aire','Existencia de estudios de rediseño y modernización de la red de monitoreo de calidad de aire','Si / No','Anual','Documento que oficialice el informe final del estudio de rediseño y modernización de la red de monitoreo de calidad del aire','No Regulatoria'),
	 (35,9,'51','Política Pública','Elaboración norma primaria de la calidad del aire COVS','Existencia de resolución de inicio de elaboración de NPC COV','Si / No','Única','a) Resolución de inicio de elaboración de NPC COV b) Conformación de comité operativo de la NPC COVs','No Regulatoria'),
	 (36,9,'51','Estudios','Rediseño y modernización del monitoreo de la calidad del aire','Porcentaje de cumplimiento de implementación de acciones de monitoreo de calidad del aire y meteorología','[Numero de acciones ejecutadas para la nueva red de monitoreo] / [ Numero de acciones propuestas a implementar para para mejorar la red de monitoreo de calidad del aire y meteorología]','Única','Resolución del MMA que oficializa las acciones necesarias para implementar la nueva red','No Regulatoria'),
	 (37,9,'54','Educación y difusión','Involucramiento de la ciudadanía','Implementación del programa comunitario y de educación ambiental','Si / No','Anual','a) Programa de involucramiento comunitario y educación ambiental de año t. b) Documento que dé cuenta de la ejecución del programa de involucramiento comunitario y educación ambiental de año t.','No Regulatoria'),
	 (38,15,'36','','Aprobación de técnica para impedir emisiones de COV en Titulares de sistema de tratamiento de aguas residuales existentes','Resolución de la SEREMI MA, que aprueba la implementación de la mejor técnica para impedir la emisión de COV al exterior, para instalaciones existentes','Si/No','Única','a) Resolución de la SEREMI MA, de aprobación de la implementación de la mejor medida. b) Programa de mantención y operación que asegura l efectividad del sistema','Regulatoria'),
	 (39,15,'36','','Aprobación de técnica para impedir emisiones de COV en Titulares de sistema de tratamiento de aguas residuales nuevas','Resolución de la SEREMI MA, que aprueba la implementación de la mejor técnica para impedir la emisión de COV al exterior, para instalaciones nuevas','Sí/No','Única','a) Resolución de la SEREMI MA, de aprobación de la implementación de la mejor medida. b) Programa de mantención y operación que asegura l efectividad del sistema','Regulatoria'),
	 (40,15,'43, 44','','Aprobación Programa de compensación de emisiones','Número de programas de compensación de emisiones aprobados','Suma del número total de programas de compensación de emisiones aprobados','Anual','Resolución de la SEREMI MA, de aprobación del programa de compensación','Regulatoria');
INSERT INTO public.medidas (id_medida,id_organismo,referencia_pda,tipo_medida,nombre_corto,indicador,formula,frecuencia,verificacion,regulatoria) VALUES
	 (41,15,'49','','Aprobación Planes Operacionales','Porcentaje de Planes aprobados en el año t','Número de resoluciones que aprueban plan operacional en el año t/N° de empresas que presentan plan operacional en el año t','Anual','Resoluciones que aprueban los Planes Operacionales en el año t (quienes contaban con Resolución Sanitaria o fuentes existentes que debían presentar Plan Operacional)','Regulatoria'),
	 (42,15,'49','','Planes operacionales para establecimientos existentes, modificaciones que sometan al SEIA y establecimientos nuevos que deban someterse al SEIA','Número de planes Operacionales presentados en el año t por titulares de proyecto sometidos al SEIA','Suma del número de planes operacionales presentados t por titulares de proyectos sometidos al SEIA','Anual','Resoluciones que aprueban los Planes Operacionales en el año t (fuentes nuevas y/o modificaciones)','Regulatoria'),
	 (43,15,'51','','Incluir en evaluación ambiental monitoreo de la calidad del aire','Pronunciamiento respecto a exigencias de monitoreo de calidad del aire en el año t','Si/No','Anual','Registro de los Oficio con pronunciamiento respecto a las exigencias de monitoreo de calidad del aire que deban cumplir los proponentes','Regulatoria'),
	 (44,15,'29','Política Pública','Informe favorable del sistema de control de MP de almacenamiento de graneles sólido','Informe favorable de la SEREMI de Medio Ambiente, del sistema y el mecanismo de verificación','Si/No','Única','Informes favorables de la SEREMI de Medio Ambiente, del sistema y el mecanismo de verificación','No Regulatoria'),
	 (45,15,'31','Política Pública','Actualización de Guía de buenas prácticas en almacenamiento, transporte y manipulación de graneles sólido en instalaciones industriales','Guía actualizada de buenas prácticas en el almacenamiento, transporte y manipulación graneles sólidos en instalaciones industriales','Si/No','Única','Oficialización de la actualización de la Guía de Buenas Prácticas del art. 31 Guía actualizada','No Regulatoria'),
	 (46,15,'32','Política Pública','Informe anual de emisiones de COVS','Informe anual de las declaraciones de emisiones de COV del año t','Si/No','Anual','Oficio de envío al MMA del informe anual de Declaraciones de Emisiones de COV, en cumplimiento al D.S N° 138/2005, RESPECTO DEL CUMPLIMIENTO DE LAS DISPOSICIONES DEL ART.32','No Regulatoria'),
	 (47,15,'41','Política Pública','Catastro calefactores a leña en zona urbana','Existencia de Catastro de calefactores a leña en zona urbana de comunas de Concón, Quintero y Puchuncaví','Si/No','Única','Registro de calefactores a leña en la zona urbana de las comunas de Concón, Quintero y Puchuncaví','No Regulatoria'),
	 (48,15,'41','Política Pública','FNDR Recambio de calefactores','Postulación al FNDR solicitud para financiar programa de recambio de calefactores','Si/No','Única','Oficio ingreso Gobierno Regional con la postulación del recambio de calefactores','No Regulatoria'),
	 (49,15,'43','Política Pública','Remisión de la resolución que aprueba programa de compensaciones','N° de resoluciones aprobatorias de PCE remitidas a la SMA','N° de resoluciones aprobatorias de PCE remitidas a la SMA en el año t/Total de programas de compensación aprobados en el año t','Anual','a) Resoluciones que aprueban programas de compensación b) Registro de los oficios donde se remiten las resoluciones de aprobación de PCE a la SMA','No Regulatoria'),
	 (50,15,'43','Política Pública','Publicaciones resoluciones que aprueba programa de compensación de emisiones','Publicación de resoluciones de Sitio web','Si/No','Anual','Sitio web de la SEREMI MA con publicación de resoluciones de PCE aprobadas anualmente','No Regulatoria');
INSERT INTO public.medidas (id_medida,id_organismo,referencia_pda,tipo_medida,nombre_corto,indicador,formula,frecuencia,verificacion,regulatoria) VALUES
	 (51,15,'46a, 50','Política Pública','Sistema de seguimiento de calidad del aire','Informe con resultados del seguimiento del sistema de la calidad del aire para P10, MP 2.5 y SO2','Si/No','Anual','a) Informe con estado de calidad del aire en el año calendario t que indique número de alertas premergencias y emergencias','No Regulatoria'),
	 (52,15,'46b','Política Pública','Resolución condiciones de ventilación','Existencia de Resolución anual que establece criterios para determinar condiciones de ventilación','Si/No','Anual','Publicación en el Diario Oficial Resolución que establece los criterios para determinar las condiciones de ventilación en el año t','No Regulatoria'),
	 (53,15,'48a','Política Pública','Informe de calidad del aire y pronóstico meteorológico','Existencia de Informe sobre calidad del aire y condiciones meteorológicas al delegado Presidencial','Si/No','Anual','a) Reportes con Pronóstico meteorológico b) Informe con condiciones de calidad del aire','No Regulatoria'),
	 (54,15,'49','Política Pública','Remisión planes operaciones','Porcentaje de planes operacionales aprobados en el año t remitidos a la SMA','Número de planes operacionales aprobados remitidos a la SMA en el año t / N° de planes operacionales aprobados en el año t','Anual','a) Resoluciones que aprueban los planes operacionales en el año t, con copia a la SMA','No Regulatoria'),
	 (55,15,'52','Política Pública','Actualización inventario de emisiones principales fuentes emisoras','Existencia de inventario de emisiones actualizado para MP, NOx, SO2 y COVs de las principales fuentes emisoras de la zona saturada','Si/No','Anual','Elaboración y publicación sitio web informe final inventario de emisiones de las principales fuentes emisoras la zona saturada','No Regulatoria'),
	 (56,15,'52','Política Pública','Actualización inventario de emisiones todas fuentes emisoras','Existencia de inventario de emisiones actualizado para MP, NOx, SO2 y COVs para todas las fuentes emisoras afectadas al plan en la zona saturada','Si/No','Cada/ 5 años','Elaboración y publicación sitio web informe final inventario de emisiones de las principales fuentes emisoras la zona saturada','No Regulatoria'),
	 (57,15,'53','Educación y difusión','Plataforma de información a la ciudadanía','Existencia de Plataforma de información a la ciudadanía','Si/No','Anual','a) Registro de dirección URL de la página web con los contenidos indicadas en el artículo 53 b) Contador del número de visitas a la página web en el año t','No Regulatoria');
