# Generated by Django 5.1.5 on 2025-04-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('formula_calculo', models.TextField()),
                ('medio_verificacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('id_organismo', models.IntegerField()),
                ('referencia_pda', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_medida', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_corto', models.CharField(blank=True, max_length=255, null=True)),
                ('indicador', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=255, null=True)),
                ('verificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('regulatoria', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id_organismo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'organismos',
            },
        ),
        migrations.CreateModel(
            name='Cumplimiento',
            fields=[
                ('id_cumplimiento', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.medida')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('año_calendario', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('id_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.medida')),
                ('id_organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.organismo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('organismo_asociado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexiones.organismo')),
            ],
        ),
    ]
