# Generated by Django 5.1.5 on 2025-04-22 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('formula_calculo', models.TextField()),
                ('medio_verificacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'organismos',
            },
        ),
        migrations.CreateModel(
            name='PeriodoPPDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('inicio_periodo', models.DateField()),
                ('fin_periodo', models.DateField()),
            ],
            options={
                'db_table': 'periodos_ppda',
            },
        ),
        migrations.CreateModel(
            name='PPDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'ppda',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referencia_pda', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_medida', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_corto', models.CharField(blank=True, max_length=255, null=True)),
                ('frecuencia', models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20, null=True)),
                ('regulatoria', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL)),
                ('indicador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexiones.indicador')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.organismo')),
                ('periodo_ppda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conexiones.periodoppda')),
                ('ppda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conexiones.ppda')),
            ],
            options={
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Cumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.medida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='periodoppda',
            name='ppda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.ppda'),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('año_calendario', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('rechazado', 'Rechazado'), ('aceptado', 'Aceptado')], max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.medida')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.organismo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('coordinador', 'Coordinador'), ('analista', 'Analista'), ('externo', 'Externo')], max_length=20)),
                ('organismo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexiones.organismo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_perfil',
            },
        ),
        migrations.CreateModel(
            name='AsignacionIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.indicador')),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.organismo')),
            ],
            options={
                'db_table': 'asignaciones_indicador',
                'unique_together': {('organismo', 'indicador')},
            },
        ),
    ]
