# Generated by Django 5.1.5 on 2025-01-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organismo',
            name='contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='organismo',
            table='organismos',
        ),
    ]
