# Generated by Django 5.1.5 on 2025-04-07 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='id_organismo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.organismo'),
        ),
    ]
