# Generated by Django 5.1.5 on 2025-04-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexiones', '0002_alter_medida_id_organismo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medida',
            old_name='id_organismo',
            new_name='organismo',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='verificacion',
        ),
        migrations.AlterField(
            model_name='medida',
            name='indicador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conexiones.indicador'),
        ),
    ]
