# Generated by Django 5.1.5 on 2025-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexiones', '0003_rename_id_organismo_medida_organismo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('rechazado', 'Rechazado'), ('aceptado', 'Aceptado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('coordinador', 'Coordinador'), ('analista', 'Analista'), ('externo', 'Externo')], max_length=20),
        ),
    ]
