# Generated by Django 5.1.5 on 2025-04-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexiones', '0004_alter_medida_frecuencia_alter_reporte_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoPPDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('inicio_periodo', models.DateField()),
                ('fin_periodo', models.DateField()),
            ],
            options={
                'db_table': 'periodos_ppda',
            },
        ),
        migrations.CreateModel(
            name='PPDA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'ppda',
            },
        ),
        migrations.AddField(
            model_name='medida',
            name='periodo_ppda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conexiones.periodoppda'),
        ),
        migrations.AddField(
            model_name='periodoppda',
            name='ppda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conexiones.ppda'),
        ),
        migrations.AddField(
            model_name='medida',
            name='ppda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conexiones.ppda'),
        ),
    ]
