# Generated by Django 5.1.5 on 2025-04-07 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexiones', '0005_periodoppda_ppda_medida_periodo_ppda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumplimiento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to='conexiones.usuario'),
        ),
        migrations.AddField(
            model_name='cumplimiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cumplimiento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to='conexiones.usuario'),
        ),
        migrations.AddField(
            model_name='cumplimiento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medida',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to='conexiones.usuario'),
        ),
        migrations.AddField(
            model_name='medida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to='conexiones.usuario'),
        ),
        migrations.AddField(
            model_name='medida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ppda',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to='conexiones.usuario'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to='conexiones.usuario'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
